### ISSUE TITLE
Fannypack Roadmap

### ISSUE THREAD

**Issue by jxom** [fannypackui/fannypack#1]
Feel free to build any uncompleted component below. If you would like to take on a component, please comment which component you would like to take (make sure nobody has mentioned it in the comments too!). Once you have commented, please raise an issue with the title 'Add <{Component}>', and I will label this as 'in-progress'.

## Primitives

These will just be an export of Reakit's primitive components (we are including them for ease of development):

- [x] `<Box>`
- [x] `<Block>`
- [x] `<InlineBlock>`
- [x] `<Flex>`
- [x] `<InlineFlex>`
- [x] `<Grid>`

## Layout

- [x] `<Columns>`
- [x] `<Column>`
- [x] `<Container>`
- [x] `<Pane>`

## Typography

- [x] `<Blockquote>`
- [x] `<Code>`
- [x] `<Heading>`
- [x] `<Link>`
- [x] `<List>`
- [x] `<Paragraph>`
- [x] `<Text>`

## Components

- [x] `<Accordians>`
- [x] `<Alert>`
- [x] `<Avatar>`
- [x] `<Breadcrumbs>`
- [x] `<Button>`
- [x] `<Callout>`
- [x] `<CalloutOverlay>`
- [x] `<Card>`
- [x] `<Dialog>`
- [x] `<DialogModal>`
- [x] `<Divider>`
- [x] `<Icon>`
- [x] `<Image>`
- [x] `<Menu>` (note: include example with Popover)
- [ ] `<Navbar>`
- [x] `<Navigation>`
- [ ] `<Pagination>`
- [x] `<Spinner>`
- [x] `<Table>`
- [x] `<Tabs>`
- [x] `<Tag>`
- [x] `<Toast>`

## Form

- [x] `<Label>`
- [x] `<Checkbox>`
  - [x] `<CheckboxField>`
- [x] `<Radio>`
  - [x] `<RadioGroup>`
  - [x] `<RadioGroupField>`
- [x] `<Select>`
  - [x] `<SelectField>`
- [x] `<SelectMenu>`
- [x] `<Switch>`
  - [x] `<SwitchField>`
- [x] `<Input>`
  - [x] `<InputField>`
- [x] `<Textarea>`
  - [x] `<TextareaField>`
- [x] `<Field>`

## Utilities

- [x] `<Badge>`
- [x] `<Backdrop>` (from Reakit)
- [x] `<Group>`
- [x] `<Hidden>` (from Reakit)
- [x] `<Modal>`
- [x] `<Overlay>` (from Reakit)
- [x] `<Portal>` (from Reakit)
- [x] `<Popover>` (from Reakit)
- [x] `<Sidebar>` (from Reakit)
- [ ] `<Step>` (from Reakit)
- [x] `<Tooltip>` (from Reakit)

## Extras

- [x] `<Timeline>`
- [x] `<Rating>`

## Misc 

- [x] Ability to import on a per-component basis for consumers who don't support tree shaking (e.g. `import Button from 'fannypack/Button'`

**Comment by Michaeltym** [comment]
@jxom i'm going to build `Alert` component

**Comment by wezpyke** [comment]
@jxom I'll pick up Textarea.

**Comment by samantha-wong** [comment]
@jxom I will build `Card`

**Comment by jxom** [comment]
@wezpyke - are you still wanting to do Textarea?

**Comment by wezpyke** [comment]
@jxom Yes, sorry for the delay.

**Comment by samantha-wong** [comment]
I dibs Avatar

**Comment by danielagattoni** [comment]
@jxom  I'll work on `<Timeline>`

**Comment by samantha-wong** [comment]
Callout!

**Comment by danielagattoni** [comment]
I'd like to contribute with `Breadcrumb` component.  is it available? cc: @jxom

**Comment by jxom** [comment]
Go for it!

**Comment by danielagattoni** [comment]
is `Accordians` still up Up for grabs  ? I'd like to contribute on that @jxom

**Comment by danielagattoni** [comment]
* Accordians in progress!!
