### ISSUE TITLE
Migration to Reakit v1

### ISSUE THREAD

**Issue by jxom** [fannypackui/fannypack#84]
Reakit v1 was released a few weeks ago now, so I think it would be nice to start to think about migrating from v0 to v1. 

See the [Reakit v1 migration guide here](https://github.com/reakit/reakit/issues/350)

I anticipate that this migration will be an incremental migration, starting with the Fannypack foundation, then moving to a per-component basis.

[Here is the Reakit v1 branch](https://github.com/fannypackui/fannypack/tree/reakit-v1)

Below are the high-level steps to achieving the migration:

#### Foundation

- [x] Install Reakit v1 on an aliased package (`reakit-next@npm:reakit@beta`) 
- [x] Add in the Reakit v1 `Provider`
- [ ] Use `styled-components` independently
  - NOTE: We will probably migrate to `styled-components` once v0 is fully out, and still depend on `reakit/styled` in the meantime. 
- [ ] Utility to wrap a Reakit component with reset styling, CSS props & spacing/color/font style overrides.

#### Primitives

- [ ] Create a `Box` component
  - Wraps around Reakit v1's `Box`
  - The reason why we won't directly export Reakit v1's `Box` is because it now doesn't come with reset styles, inbuilt CSS props & Fannypacks spacing/color overrides.
- [ ] Create `Block`, `InlineBlock`, `Inline`, `Flex`, `InlineFlex`, `Grid` components 
  - These primitives are now removed in Reakit v1
  - It will use Fannypack's `Box`

#### Typography

TODO

#### Layout

TODO

#### Components

TODO

#### Form 

TODO

#### Utilities

TODO 

#### Templates

TODO

**Comment by jxom** [comment]
Closing in favour of #92
